schema_version = "1.0.0"

id = "quickmenu"
version = "3.1.2"
name = "Quick Menu"
tagline = "Simplifies access to useful operators and adds new functionality"
maintainer = "passivestar"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]